<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>FuelPHP Framework</title>
	<style type="text/css">
		* { margin: 0; padding: 0; }
		body { background-color: #EEE; font-family: sans-serif; font-size: 16px; line-height: 20px; margin: 40px; }
		#wrapper { padding: 30px; background: #fff; color: #333; border: 1px solid #ccc; margin: 0 auto; width: 800px; }
		a { color: #36428D; }
		h1 { color: #000; font-size: 55px; padding: 0 0 25px; line-height: 1em; }
		.intro { font-size: 22px; line-height: 30px; font-family: georgia, serif; color: #555; padding: 29px 0 20px; border-top: 1px solid #CCC; }
		h2 { margin: 50px 0 15px; padding: 0 0 10px; font-size: 18px; border-bottom: 1px dashed #ccc; }
		h2.first { margin: 10px 0 15px; }
		p { margin: 0 0 15px; line-height: 22px;}
		a { color: #666; }
		pre { border-left: 1px solid #ddd; line-height:20px; margin:20px; padding-left:1em; font-size: 16px; }
		pre, code { color:#137F80; font-family: Courier, monospace; }
		ul, ol { margin: 15px 30px; }
		li { line-height: 24px;}
		.footer { color: #777; font-size: 12px; margin: 40px 0 0 0; }
		pre.fuel_debug_source { border: 1px solid #CCCCCC; background-color: #FFFFFF; color: #333333; font-family: monospace; font-size: 11px; line-height: 1em; margin: 0; padding: 0; width: 100%; overflow: auto; }
		span.fuel_line { display: block; margin: 0px; padding: 0px; }
		span.fuel_line_number { display: inline-block; background-color: #EFEFEF; padding: 4px 8px 4px 8px; }
		span.fuel_line_content { display: inline-block; padding: 4px 0 4px 4px; }
		span.fuel_current_line span.fuel_line_number, span.fuel_current_line { background-color: #f0eb96; font-weight: bold; }
		.backtrace_block { display: none; }
	</style>
	<script type="text/javascript">
		function fuel_toggle(elem){elem = document.getElementById(elem);if (elem.style && elem.style['display']){var disp = elem.style['display'];}else if (elem.currentStyle){var disp = elem.currentStyle['display'];}else if (window.getComputedStyle){var disp = document.defaultView.getComputedStyle(elem, null).getPropertyValue('display');}elem.style.display = disp == 'block' ? 'none' : 'block';return false;}
	</script>
</head>
<body>
	<div id="wrapper">
		<h1>Error!</h1>

		<p class="intro">ParseError [ Error ]:<br />syntax error, unexpected end of file, expecting function (T_FUNCTION)</p>

		<h2 class="first">APPPATH/classes/model/roles.php @ line 21</h2>

<pre class="fuel_debug_source"><span class="fuel_line"><span class="fuel_line_number">16</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #DD0000">'model_to'&nbsp;</span><span style="color: #007700">=&gt;&nbsp;</span><span style="color: #DD0000">'Model_Users'</span><span style="color: #007700">,</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">17</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #DD0000">'key_to'&nbsp;</span><span style="color: #007700">=&gt;&nbsp;</span><span style="color: #DD0000">'id_role'</span><span style="color: #007700">,</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">18</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #DD0000">'cascade_save'&nbsp;</span><span style="color: #007700">=&gt;&nbsp;</span><span style="color: #0000BB">true</span><span style="color: #007700">,</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">19</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #DD0000">'cascade_delete'&nbsp;</span><span style="color: #007700">=&gt;&nbsp;</span><span style="color: #0000BB">false</span><span style="color: #007700">,</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">20</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">)</span></span>
</span></span><span class="fuel_line fuel_current_line"><span class="fuel_line_number">21</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span><span style="color: #007700">);</span></span>
</span></span></pre>
		<h2>Backtrace</h2>
		<ol>
					<li>
				<a href="#" onclick="javascript:fuel_toggle('backtrace_1');return false;">COREPATH/classes/autoloader.php @ line 283</a>
				<div id="backtrace_1" class="backtrace_block">
<pre class="fuel_debug_source"><span class="fuel_line"><span class="fuel_line_number">278</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">{</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">279</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$path&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">APPPATH</span><span style="color: #007700">.</span><span style="color: #DD0000">'classes'</span><span style="color: #007700">.</span><span style="color: #0000BB">DS</span><span style="color: #007700">.static::</span><span style="color: #0000BB">class_to_path</span><span style="color: #007700">(</span><span style="color: #0000BB">$class</span><span style="color: #007700">);</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">280</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">281</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">if&nbsp;(</span><span style="color: #0000BB">is_file</span><span style="color: #007700">(</span><span style="color: #0000BB">$path</span><span style="color: #007700">))</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">282</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">{</span></span>
</span></span><span class="fuel_line fuel_current_line"><span class="fuel_line_number">283</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">static::</span><span style="color: #0000BB">init_class</span><span style="color: #007700">(</span><span style="color: #0000BB">$class</span><span style="color: #007700">,&nbsp;</span><span style="color: #0000BB">$path</span><span style="color: #007700">);</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">284</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$loaded&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">true</span><span style="color: #007700">;</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">285</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">286</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">287</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">288</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span></pre>
				</div>
			</li>
					<li>
				<a href="#" onclick="javascript:fuel_toggle('backtrace_2');return false;">APPPATH/classes/controller/users.php @ line 33</a>
				<div id="backtrace_2" class="backtrace_block">
<pre class="fuel_debug_source"><span class="fuel_line"><span class="fuel_line_number">28</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">29</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">30</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$user&nbsp;</span><span style="color: #007700">=&nbsp;new&nbsp;</span><span style="color: #0000BB">Model_Users</span><span style="color: #007700">();</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">31</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$user</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">name&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">$name</span><span style="color: #007700">;</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">32</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$user</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">password&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">$password</span><span style="color: #007700">;</span></span>
</span></span><span class="fuel_line fuel_current_line"><span class="fuel_line_number">33</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$user</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">role&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">Model_Roles</span><span style="color: #007700">::</span><span style="color: #0000BB">find</span><span style="color: #007700">(</span><span style="color: #0000BB">$role</span><span style="color: #007700">);</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">34</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$user</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">save</span><span style="color: #007700">();</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">35</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$json&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">response</span><span style="color: #007700">(array(</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">36</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #DD0000">'code'&nbsp;</span><span style="color: #007700">=&gt;&nbsp;</span><span style="color: #0000BB">201</span><span style="color: #007700">,</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">37</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #DD0000">'message'&nbsp;</span><span style="color: #007700">=&gt;&nbsp;</span><span style="color: #DD0000">'usuario&nbsp;creado'</span><span style="color: #007700">,</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">38</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #DD0000">'name'&nbsp;</span><span style="color: #007700">=&gt;&nbsp;</span><span style="color: #0000BB">$input</span><span style="color: #007700">[</span><span style="color: #DD0000">'name'</span><span style="color: #007700">],</span></span>
</span></span></pre>
				</div>
			</li>
					<li>
				<a href="#" onclick="javascript:fuel_toggle('backtrace_3');return false;">COREPATH/base56.php @ line 37</a>
				<div id="backtrace_3" class="backtrace_block">
<pre class="fuel_debug_source"><span class="fuel_line"><span class="fuel_line_number">32</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$args&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">array_values</span><span style="color: #007700">(</span><span style="color: #0000BB">$args</span><span style="color: #007700">);</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">33</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">34</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">35</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">list(</span><span style="color: #0000BB">$instance</span><span style="color: #007700">,&nbsp;</span><span style="color: #0000BB">$method</span><span style="color: #007700">)&nbsp;=&nbsp;</span><span style="color: #0000BB">$callback</span><span style="color: #007700">;</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">36</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line fuel_current_line"><span class="fuel_line_number">37</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">return&nbsp;</span><span style="color: #0000BB">$instance</span><span style="color: #007700">-&gt;{</span><span style="color: #0000BB">$method</span><span style="color: #007700">}(...</span><span style="color: #0000BB">$args</span><span style="color: #007700">);</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">38</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">39</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">40</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #FF8000">//&nbsp;static&nbsp;call?</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">41</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">elseif&nbsp;(</span><span style="color: #0000BB">is_array</span><span style="color: #007700">(</span><span style="color: #0000BB">$callback</span><span style="color: #007700">)&nbsp;and&nbsp;isset(</span><span style="color: #0000BB">$callback</span><span style="color: #007700">[</span><span style="color: #0000BB">1</span><span style="color: #007700">])&nbsp;and&nbsp;</span><span style="color: #0000BB">is_string</span><span style="color: #007700">(</span><span style="color: #0000BB">$callback</span><span style="color: #007700">[</span><span style="color: #0000BB">0</span><span style="color: #007700">]))</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">42</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">{</span></span>
</span></span></pre>
				</div>
			</li>
					<li>
				<a href="#" onclick="javascript:fuel_toggle('backtrace_4');return false;">COREPATH/classes/controller/rest.php @ line 153</a>
				<div id="backtrace_4" class="backtrace_block">
<pre class="fuel_debug_source"><span class="fuel_line"><span class="fuel_line_number">148</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">149</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">150</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #FF8000">//&nbsp;If&nbsp;method&nbsp;is&nbsp;not&nbsp;available,&nbsp;set&nbsp;status&nbsp;code&nbsp;to&nbsp;404</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">151</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">if&nbsp;(</span><span style="color: #0000BB">method_exists</span><span style="color: #007700">(</span><span style="color: #0000BB">$this</span><span style="color: #007700">,&nbsp;</span><span style="color: #0000BB">$controller_method</span><span style="color: #007700">))</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">152</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">{</span></span>
</span></span><span class="fuel_line fuel_current_line"><span class="fuel_line_number">153</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">return&nbsp;</span><span style="color: #0000BB">call_fuel_func_array</span><span style="color: #007700">(array(</span><span style="color: #0000BB">$this</span><span style="color: #007700">,&nbsp;</span><span style="color: #0000BB">$controller_method</span><span style="color: #007700">),&nbsp;</span><span style="color: #0000BB">$arguments</span><span style="color: #007700">);</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">154</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">155</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">else</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">156</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">{</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">157</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">response</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">status&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">no_method_status</span><span style="color: #007700">;</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">158</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">return;</span></span>
</span></span></pre>
				</div>
			</li>
					<li>
				<a href="#" onclick="javascript:fuel_toggle('backtrace_5');return false;">COREPATH/classes/request.php @ line 454</a>
				<div id="backtrace_5" class="backtrace_block">
<pre class="fuel_debug_source"><span class="fuel_line"><span class="fuel_line_number">449</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #FF8000">//&nbsp;fire&nbsp;any&nbsp;controller&nbsp;started&nbsp;events</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">450</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">\</span><span style="color: #0000BB">Event</span><span style="color: #007700">::</span><span style="color: #0000BB">instance</span><span style="color: #007700">()-&gt;</span><span style="color: #0000BB">has_events</span><span style="color: #007700">(</span><span style="color: #DD0000">'controller_started'</span><span style="color: #007700">)&nbsp;and&nbsp;\</span><span style="color: #0000BB">Event</span><span style="color: #007700">::</span><span style="color: #0000BB">instance</span><span style="color: #007700">()-&gt;</span><span style="color: #0000BB">trigger</span><span style="color: #007700">(</span><span style="color: #DD0000">'controller_started'</span><span style="color: #007700">,&nbsp;</span><span style="color: #DD0000">''</span><span style="color: #007700">,&nbsp;</span><span style="color: #DD0000">'none'</span><span style="color: #007700">);</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">451</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">452</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$class</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">hasMethod</span><span style="color: #007700">(</span><span style="color: #DD0000">'before'</span><span style="color: #007700">)&nbsp;and&nbsp;</span><span style="color: #0000BB">$class</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">getMethod</span><span style="color: #007700">(</span><span style="color: #DD0000">'before'</span><span style="color: #007700">)-&gt;</span><span style="color: #0000BB">invoke</span><span style="color: #007700">(</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">controller_instance</span><span style="color: #007700">);</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">453</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line fuel_current_line"><span class="fuel_line_number">454</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$response&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">$action</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">invokeArgs</span><span style="color: #007700">(</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">controller_instance</span><span style="color: #007700">,&nbsp;</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">method_params</span><span style="color: #007700">);</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">455</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">456</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$class</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">hasMethod</span><span style="color: #007700">(</span><span style="color: #DD0000">'after'</span><span style="color: #007700">)&nbsp;and&nbsp;</span><span style="color: #0000BB">$response&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">$class</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">getMethod</span><span style="color: #007700">(</span><span style="color: #DD0000">'after'</span><span style="color: #007700">)-&gt;</span><span style="color: #0000BB">invoke</span><span style="color: #007700">(</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">controller_instance</span><span style="color: #007700">,&nbsp;</span><span style="color: #0000BB">$response</span><span style="color: #007700">);</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">457</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">458</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #FF8000">//&nbsp;fire&nbsp;any&nbsp;controller&nbsp;finished&nbsp;events</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">459</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">\</span><span style="color: #0000BB">Event</span><span style="color: #007700">::</span><span style="color: #0000BB">instance</span><span style="color: #007700">()-&gt;</span><span style="color: #0000BB">has_events</span><span style="color: #007700">(</span><span style="color: #DD0000">'controller_finished'</span><span style="color: #007700">)&nbsp;and&nbsp;\</span><span style="color: #0000BB">Event</span><span style="color: #007700">::</span><span style="color: #0000BB">instance</span><span style="color: #007700">()-&gt;</span><span style="color: #0000BB">trigger</span><span style="color: #007700">(</span><span style="color: #DD0000">'controller_finished'</span><span style="color: #007700">,&nbsp;</span><span style="color: #DD0000">''</span><span style="color: #007700">,&nbsp;</span><span style="color: #DD0000">'none'</span><span style="color: #007700">);</span></span>
</span></span></pre>
				</div>
			</li>
					<li>
				<a href="#" onclick="javascript:fuel_toggle('backtrace_6');return false;">DOCROOT/index.php @ line 71</a>
				<div id="backtrace_6" class="backtrace_block">
<pre class="fuel_debug_source"><span class="fuel_line"><span class="fuel_line_number">66</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$response&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">Response</span><span style="color: #007700">::</span><span style="color: #0000BB">forge</span><span style="color: #007700">(</span><span style="color: #0000BB">$response</span><span style="color: #007700">);</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">67</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">68</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">69</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">elseif&nbsp;(</span><span style="color: #0000BB">$e&nbsp;</span><span style="color: #007700">===&nbsp;</span><span style="color: #0000BB">false</span><span style="color: #007700">)</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">70</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">{</span></span>
</span></span><span class="fuel_line fuel_current_line"><span class="fuel_line_number">71</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$response&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">Request</span><span style="color: #007700">::</span><span style="color: #0000BB">forge</span><span style="color: #007700">()-&gt;</span><span style="color: #0000BB">execute</span><span style="color: #007700">()-&gt;</span><span style="color: #0000BB">response</span><span style="color: #007700">();</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">72</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">73</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">elseif&nbsp;(</span><span style="color: #0000BB">$route</span><span style="color: #007700">)</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">74</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">{</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">75</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$response&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">Request</span><span style="color: #007700">::</span><span style="color: #0000BB">forge</span><span style="color: #007700">(</span><span style="color: #0000BB">$route</span><span style="color: #007700">,&nbsp;</span><span style="color: #0000BB">false</span><span style="color: #007700">)-&gt;</span><span style="color: #0000BB">execute</span><span style="color: #007700">(array(</span><span style="color: #0000BB">$e</span><span style="color: #007700">))-&gt;</span><span style="color: #0000BB">response</span><span style="color: #007700">();</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">76</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span></pre>
				</div>
			</li>
					<li>
				<a href="#" onclick="javascript:fuel_toggle('backtrace_7');return false;">DOCROOT/index.php @ line 92</a>
				<div id="backtrace_7" class="backtrace_block">
<pre class="fuel_debug_source"><span class="fuel_line"><span class="fuel_line_number">87</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span><span style="color: #007700">{</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">88</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #FF8000">//&nbsp;Boot&nbsp;the&nbsp;app...</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">89</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">require&nbsp;</span><span style="color: #0000BB">APPPATH</span><span style="color: #007700">.</span><span style="color: #DD0000">'bootstrap.php'</span><span style="color: #007700">;</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">90</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">91</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #FF8000">//&nbsp;...&nbsp;and&nbsp;execute&nbsp;the&nbsp;main&nbsp;request</span></span>
</span></span><span class="fuel_line fuel_current_line"><span class="fuel_line_number">92</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;$response&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">$routerequest</span><span style="color: #007700">();</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">93</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">94</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span><span style="color: #007700">catch&nbsp;(</span><span style="color: #0000BB">HttpBadRequestException&nbsp;$e</span><span style="color: #007700">)</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">95</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span><span style="color: #007700">{</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">96</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;$response&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">$routerequest</span><span style="color: #007700">(</span><span style="color: #DD0000">'_400_'</span><span style="color: #007700">,&nbsp;</span><span style="color: #0000BB">$e</span><span style="color: #007700">);</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">97</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span><span style="color: #007700">}</span></span>
</span></span></pre>
				</div>
			</li>
				</ol>


	<h2>Prior Contents (<a href="#" onclick="javascript:fuel_toggle('prior_contents');return false;">show</a>)</h2>
				<pre id="prior_contents" class="fuel_debug_source" style="display: none;"> </pre>
	
		<p class="footer">
			<a href="http://fuelphp.com">FuelPHP</a> is released under the MIT license.
		</p>
	</div>
</body>
</html>
