<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>FuelPHP Framework</title>
	<style type="text/css">
		* { margin: 0; padding: 0; }
		body { background-color: #EEE; font-family: sans-serif; font-size: 16px; line-height: 20px; margin: 40px; }
		#wrapper { padding: 30px; background: #fff; color: #333; border: 1px solid #ccc; margin: 0 auto; width: 800px; }
		a { color: #36428D; }
		h1 { color: #000; font-size: 55px; padding: 0 0 25px; line-height: 1em; }
		.intro { font-size: 22px; line-height: 30px; font-family: georgia, serif; color: #555; padding: 29px 0 20px; border-top: 1px solid #CCC; }
		h2 { margin: 50px 0 15px; padding: 0 0 10px; font-size: 18px; border-bottom: 1px dashed #ccc; }
		h2.first { margin: 10px 0 15px; }
		p { margin: 0 0 15px; line-height: 22px;}
		a { color: #666; }
		pre { border-left: 1px solid #ddd; line-height:20px; margin:20px; padding-left:1em; font-size: 16px; }
		pre, code { color:#137F80; font-family: Courier, monospace; }
		ul, ol { margin: 15px 30px; }
		li { line-height: 24px;}
		.footer { color: #777; font-size: 12px; margin: 40px 0 0 0; }
		pre.fuel_debug_source { border: 1px solid #CCCCCC; background-color: #FFFFFF; color: #333333; font-family: monospace; font-size: 11px; line-height: 1em; margin: 0; padding: 0; width: 100%; overflow: auto; }
		span.fuel_line { display: block; margin: 0px; padding: 0px; }
		span.fuel_line_number { display: inline-block; background-color: #EFEFEF; padding: 4px 8px 4px 8px; }
		span.fuel_line_content { display: inline-block; padding: 4px 0 4px 4px; }
		span.fuel_current_line span.fuel_line_number, span.fuel_current_line { background-color: #f0eb96; font-weight: bold; }
		.backtrace_block { display: none; }
	</style>
	<script type="text/javascript">
		function fuel_toggle(elem){elem = document.getElementById(elem);if (elem.style && elem.style['display']){var disp = elem.style['display'];}else if (elem.currentStyle){var disp = elem.currentStyle['display'];}else if (window.getComputedStyle){var disp = document.defaultView.getComputedStyle(elem, null).getPropertyValue('display');}elem.style.display = disp == 'block' ? 'none' : 'block';return false;}
	</script>
</head>
<body>
	<div id="wrapper">
		<h1>1044!</h1>

		<p class="intro">Fuel\Core\Database_Exception [ 1044 ]:<br />SQLSTATE[HY000] [1044] Access denied for user &#039;phpmyadmin&#039;@&#039;localhost&#039; to database &#039;chema_users_login&#039;</p>

		<h2 class="first">COREPATH/classes/database/pdo/connection.php @ line 112</h2>

<pre class="fuel_debug_source"><span class="fuel_line"><span class="fuel_line_number">107</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">else</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">108</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">{</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">109</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$error_code&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">0</span><span style="color: #007700">;</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">110</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">111</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line fuel_current_line"><span class="fuel_line_number">112</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">throw&nbsp;new&nbsp;\</span><span style="color: #0000BB">Database_Exception</span><span style="color: #007700">(</span><span style="color: #0000BB">str_replace</span><span style="color: #007700">(</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">_config</span><span style="color: #007700">[</span><span style="color: #DD0000">'connection'</span><span style="color: #007700">][</span><span style="color: #DD0000">'password'</span><span style="color: #007700">],&nbsp;</span><span style="color: #0000BB">str_repeat</span><span style="color: #007700">(</span><span style="color: #DD0000">'*'</span><span style="color: #007700">,&nbsp;</span><span style="color: #0000BB">10</span><span style="color: #007700">),&nbsp;</span><span style="color: #0000BB">$e</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">getMessage</span><span style="color: #007700">()),&nbsp;</span><span style="color: #0000BB">$error_code</span><span style="color: #007700">,&nbsp;</span><span style="color: #0000BB">$e</span><span style="color: #007700">);</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">113</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">114</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">115</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">116</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #FF8000">/**</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">117</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">*&nbsp;@return&nbsp;</span><span style="color: #0000BB">bool</span></span>
</span></span></pre>
		<h2>Backtrace</h2>
		<ol>
					<li>
				<a href="#" onclick="javascript:fuel_toggle('backtrace_1');return false;">COREPATH/classes/database/pdo/connection.php @ line 174</a>
				<div id="backtrace_1" class="backtrace_block">
<pre class="fuel_debug_source"><span class="fuel_line"><span class="fuel_line_number">169</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">*&nbsp;@</span><span style="color: #0000BB">throws&nbsp;</span><span style="color: #007700">\</span><span style="color: #0000BB">Database_Exception</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">170</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">*/</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">171</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">public&nbsp;function&nbsp;</span><span style="color: #0000BB">query</span><span style="color: #007700">(</span><span style="color: #0000BB">$type</span><span style="color: #007700">,&nbsp;</span><span style="color: #0000BB">$sql</span><span style="color: #007700">,&nbsp;</span><span style="color: #0000BB">$as_object</span><span style="color: #007700">)</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">172</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">{</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">173</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #FF8000">//&nbsp;Make&nbsp;sure&nbsp;the&nbsp;database&nbsp;is&nbsp;connected</span></span>
</span></span><span class="fuel_line fuel_current_line"><span class="fuel_line_number">174</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">_connection&nbsp;</span><span style="color: #007700">or&nbsp;</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">connect</span><span style="color: #007700">();</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">175</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">176</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">if&nbsp;(&nbsp;!&nbsp;empty(</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">_config</span><span style="color: #007700">[</span><span style="color: #DD0000">'profiling'</span><span style="color: #007700">]))</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">177</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">{</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">178</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #FF8000">//&nbsp;Get&nbsp;the&nbsp;paths&nbsp;defined&nbsp;in&nbsp;config</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">179</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$paths&nbsp;</span><span style="color: #007700">=&nbsp;\</span><span style="color: #0000BB">Config</span><span style="color: #007700">::</span><span style="color: #0000BB">get</span><span style="color: #007700">(</span><span style="color: #DD0000">'profiling_paths'</span><span style="color: #007700">);</span></span>
</span></span></pre>
				</div>
			</li>
					<li>
				<a href="#" onclick="javascript:fuel_toggle('backtrace_2');return false;">COREPATH/classes/database/query.php @ line 314</a>
				<div id="backtrace_2" class="backtrace_block">
<pre class="fuel_debug_source"><span class="fuel_line"><span class="fuel_line_number">309</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">catch&nbsp;(\</span><span style="color: #0000BB">CacheNotFoundException&nbsp;$e</span><span style="color: #007700">)&nbsp;{}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">310</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">311</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">312</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #FF8000">//&nbsp;Execute&nbsp;the&nbsp;query</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">313</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">\</span><span style="color: #0000BB">DB</span><span style="color: #007700">::</span><span style="color: #0000BB">$query_count</span><span style="color: #007700">++;</span></span>
</span></span><span class="fuel_line fuel_current_line"><span class="fuel_line_number">314</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$result&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">$db</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">query</span><span style="color: #007700">(</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">_type</span><span style="color: #007700">,&nbsp;</span><span style="color: #0000BB">$sql</span><span style="color: #007700">,&nbsp;</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">_as_object</span><span style="color: #007700">);</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">315</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">316</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #FF8000">//&nbsp;Cache&nbsp;the&nbsp;result&nbsp;if&nbsp;needed</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">317</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">if&nbsp;(isset(</span><span style="color: #0000BB">$cache</span><span style="color: #007700">)&nbsp;and&nbsp;(</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">_cache_all&nbsp;</span><span style="color: #007700">or&nbsp;</span><span style="color: #0000BB">$result</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">count</span><span style="color: #007700">()))</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">318</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">{</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">319</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$cache</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">set_expiration</span><span style="color: #007700">(</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">_lifetime</span><span style="color: #007700">)-&gt;</span><span style="color: #0000BB">set_contents</span><span style="color: #007700">(</span><span style="color: #0000BB">$result</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">as_array</span><span style="color: #007700">())-&gt;</span><span style="color: #0000BB">set</span><span style="color: #007700">();</span></span>
</span></span></pre>
				</div>
			</li>
					<li>
				<a href="#" onclick="javascript:fuel_toggle('backtrace_3');return false;">PKGPATH/orm/classes/query.php @ line 1304</a>
				<div id="backtrace_3" class="backtrace_block">
<pre class="fuel_debug_source"><span class="fuel_line"><span class="fuel_line_number">1299</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">1300</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$ref&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">$values</span><span style="color: #007700">;</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">1301</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">1302</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">1303</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line fuel_current_line"><span class="fuel_line_number">1304</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$rows&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">$query</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">execute</span><span style="color: #007700">(</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">connection</span><span style="color: #007700">)-&gt;</span><span style="color: #0000BB">as_array</span><span style="color: #007700">();</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">1305</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">1306</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #FF8000">//&nbsp;To&nbsp;workaround&nbsp;the&nbsp;PHP&nbsp;5.x&nbsp;performance&nbsp;issue&nbsp;at&nbsp;pulling&nbsp;a&nbsp;large&nbsp;number&nbsp;of&nbsp;records,</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">1307</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #FF8000">//&nbsp;we&nbsp;shouldn't&nbsp;use&nbsp;passing&nbsp;array&nbsp;by&nbsp;reference&nbsp;directly&nbsp;here.</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">1308</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$result&nbsp;</span><span style="color: #007700">=&nbsp;new&nbsp;\</span><span style="color: #0000BB">stdClass</span><span style="color: #007700">;</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">1309</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$result</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">data&nbsp;</span><span style="color: #007700">=&nbsp;array();</span></span>
</span></span></pre>
				</div>
			</li>
					<li>
				<a href="#" onclick="javascript:fuel_toggle('backtrace_4');return false;">PKGPATH/orm/classes/query.php @ line 1381</a>
				<div id="backtrace_4" class="backtrace_block">
<pre class="fuel_debug_source"><span class="fuel_line"><span class="fuel_line_number">1376</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">limit&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">1</span><span style="color: #007700">;</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">1377</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">rows_limit&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">null</span><span style="color: #007700">;</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">1378</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">1379</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">1380</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #FF8000">//&nbsp;get&nbsp;the&nbsp;result&nbsp;using&nbsp;normal&nbsp;find</span></span>
</span></span><span class="fuel_line fuel_current_line"><span class="fuel_line_number">1381</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$result&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">get</span><span style="color: #007700">();</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">1382</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">1383</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #FF8000">//&nbsp;put&nbsp;back&nbsp;the&nbsp;old&nbsp;limits</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">1384</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">limit&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">$limit</span><span style="color: #007700">;</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">1385</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">rows_limit&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">$rows_limit</span><span style="color: #007700">;</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">1386</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span></pre>
				</div>
			</li>
					<li>
				<a href="#" onclick="javascript:fuel_toggle('backtrace_5');return false;">PKGPATH/orm/classes/model.php @ line 608</a>
				<div id="backtrace_5" class="backtrace_block">
<pre class="fuel_debug_source"><span class="fuel_line"><span class="fuel_line_number">603</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">return&nbsp;static::</span><span style="color: #0000BB">$_cached_objects</span><span style="color: #007700">[</span><span style="color: #0000BB">get_called_class</span><span style="color: #007700">()][static::</span><span style="color: #0000BB">implode_pk</span><span style="color: #007700">(</span><span style="color: #0000BB">$cache_pk</span><span style="color: #007700">)];</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">604</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">605</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">606</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;array_key_exists</span><span style="color: #007700">(</span><span style="color: #DD0000">'where'</span><span style="color: #007700">,&nbsp;</span><span style="color: #0000BB">$options</span><span style="color: #007700">)&nbsp;and&nbsp;</span><span style="color: #0000BB">$where&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">array_merge</span><span style="color: #007700">(</span><span style="color: #0000BB">$options</span><span style="color: #007700">[</span><span style="color: #DD0000">'where'</span><span style="color: #007700">],&nbsp;</span><span style="color: #0000BB">$where</span><span style="color: #007700">);</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">607</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$options</span><span style="color: #007700">[</span><span style="color: #DD0000">'where'</span><span style="color: #007700">]&nbsp;=&nbsp;</span><span style="color: #0000BB">$where</span><span style="color: #007700">;</span></span>
</span></span><span class="fuel_line fuel_current_line"><span class="fuel_line_number">608</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">return&nbsp;static::</span><span style="color: #0000BB">query</span><span style="color: #007700">(</span><span style="color: #0000BB">$options</span><span style="color: #007700">)-&gt;</span><span style="color: #0000BB">get_one</span><span style="color: #007700">();</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">609</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">610</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">611</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">612</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #FF8000">/**</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">613</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">*&nbsp;</span><span style="color: #0000BB">Creates&nbsp;a&nbsp;</span><span style="color: #007700">new&nbsp;</span><span style="color: #0000BB">query&nbsp;with&nbsp;optional&nbsp;settings&nbsp;up&nbsp;front</span></span>
</span></span></pre>
				</div>
			</li>
					<li>
				<a href="#" onclick="javascript:fuel_toggle('backtrace_6');return false;">APPPATH/classes/controller/users.php @ line 33</a>
				<div id="backtrace_6" class="backtrace_block">
<pre class="fuel_debug_source"><span class="fuel_line"><span class="fuel_line_number">28</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">29</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">30</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$user&nbsp;</span><span style="color: #007700">=&nbsp;new&nbsp;</span><span style="color: #0000BB">Model_Users</span><span style="color: #007700">();</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">31</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$user</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">name&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">$name</span><span style="color: #007700">;</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">32</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$user</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">password&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">$password</span><span style="color: #007700">;</span></span>
</span></span><span class="fuel_line fuel_current_line"><span class="fuel_line_number">33</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$user</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">role&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">Model_Roles</span><span style="color: #007700">::</span><span style="color: #0000BB">find</span><span style="color: #007700">(</span><span style="color: #0000BB">$role</span><span style="color: #007700">);</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">34</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$user</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">save</span><span style="color: #007700">();</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">35</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$json&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">response</span><span style="color: #007700">(array(</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">36</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #DD0000">'code'&nbsp;</span><span style="color: #007700">=&gt;&nbsp;</span><span style="color: #0000BB">201</span><span style="color: #007700">,</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">37</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #DD0000">'message'&nbsp;</span><span style="color: #007700">=&gt;&nbsp;</span><span style="color: #DD0000">'usuario&nbsp;creado'</span><span style="color: #007700">,</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">38</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #DD0000">'name'&nbsp;</span><span style="color: #007700">=&gt;&nbsp;</span><span style="color: #0000BB">$input</span><span style="color: #007700">[</span><span style="color: #DD0000">'name'</span><span style="color: #007700">],</span></span>
</span></span></pre>
				</div>
			</li>
					<li>
				<a href="#" onclick="javascript:fuel_toggle('backtrace_7');return false;">COREPATH/base56.php @ line 37</a>
				<div id="backtrace_7" class="backtrace_block">
<pre class="fuel_debug_source"><span class="fuel_line"><span class="fuel_line_number">32</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$args&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">array_values</span><span style="color: #007700">(</span><span style="color: #0000BB">$args</span><span style="color: #007700">);</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">33</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">34</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">35</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">list(</span><span style="color: #0000BB">$instance</span><span style="color: #007700">,&nbsp;</span><span style="color: #0000BB">$method</span><span style="color: #007700">)&nbsp;=&nbsp;</span><span style="color: #0000BB">$callback</span><span style="color: #007700">;</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">36</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line fuel_current_line"><span class="fuel_line_number">37</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">return&nbsp;</span><span style="color: #0000BB">$instance</span><span style="color: #007700">-&gt;{</span><span style="color: #0000BB">$method</span><span style="color: #007700">}(...</span><span style="color: #0000BB">$args</span><span style="color: #007700">);</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">38</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">39</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">40</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #FF8000">//&nbsp;static&nbsp;call?</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">41</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">elseif&nbsp;(</span><span style="color: #0000BB">is_array</span><span style="color: #007700">(</span><span style="color: #0000BB">$callback</span><span style="color: #007700">)&nbsp;and&nbsp;isset(</span><span style="color: #0000BB">$callback</span><span style="color: #007700">[</span><span style="color: #0000BB">1</span><span style="color: #007700">])&nbsp;and&nbsp;</span><span style="color: #0000BB">is_string</span><span style="color: #007700">(</span><span style="color: #0000BB">$callback</span><span style="color: #007700">[</span><span style="color: #0000BB">0</span><span style="color: #007700">]))</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">42</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">{</span></span>
</span></span></pre>
				</div>
			</li>
					<li>
				<a href="#" onclick="javascript:fuel_toggle('backtrace_8');return false;">COREPATH/classes/controller/rest.php @ line 153</a>
				<div id="backtrace_8" class="backtrace_block">
<pre class="fuel_debug_source"><span class="fuel_line"><span class="fuel_line_number">148</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">149</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">150</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #FF8000">//&nbsp;If&nbsp;method&nbsp;is&nbsp;not&nbsp;available,&nbsp;set&nbsp;status&nbsp;code&nbsp;to&nbsp;404</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">151</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">if&nbsp;(</span><span style="color: #0000BB">method_exists</span><span style="color: #007700">(</span><span style="color: #0000BB">$this</span><span style="color: #007700">,&nbsp;</span><span style="color: #0000BB">$controller_method</span><span style="color: #007700">))</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">152</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">{</span></span>
</span></span><span class="fuel_line fuel_current_line"><span class="fuel_line_number">153</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">return&nbsp;</span><span style="color: #0000BB">call_fuel_func_array</span><span style="color: #007700">(array(</span><span style="color: #0000BB">$this</span><span style="color: #007700">,&nbsp;</span><span style="color: #0000BB">$controller_method</span><span style="color: #007700">),&nbsp;</span><span style="color: #0000BB">$arguments</span><span style="color: #007700">);</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">154</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">155</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">else</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">156</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">{</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">157</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">response</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">status&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">no_method_status</span><span style="color: #007700">;</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">158</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">return;</span></span>
</span></span></pre>
				</div>
			</li>
					<li>
				<a href="#" onclick="javascript:fuel_toggle('backtrace_9');return false;">COREPATH/classes/request.php @ line 454</a>
				<div id="backtrace_9" class="backtrace_block">
<pre class="fuel_debug_source"><span class="fuel_line"><span class="fuel_line_number">449</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #FF8000">//&nbsp;fire&nbsp;any&nbsp;controller&nbsp;started&nbsp;events</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">450</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">\</span><span style="color: #0000BB">Event</span><span style="color: #007700">::</span><span style="color: #0000BB">instance</span><span style="color: #007700">()-&gt;</span><span style="color: #0000BB">has_events</span><span style="color: #007700">(</span><span style="color: #DD0000">'controller_started'</span><span style="color: #007700">)&nbsp;and&nbsp;\</span><span style="color: #0000BB">Event</span><span style="color: #007700">::</span><span style="color: #0000BB">instance</span><span style="color: #007700">()-&gt;</span><span style="color: #0000BB">trigger</span><span style="color: #007700">(</span><span style="color: #DD0000">'controller_started'</span><span style="color: #007700">,&nbsp;</span><span style="color: #DD0000">''</span><span style="color: #007700">,&nbsp;</span><span style="color: #DD0000">'none'</span><span style="color: #007700">);</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">451</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">452</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$class</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">hasMethod</span><span style="color: #007700">(</span><span style="color: #DD0000">'before'</span><span style="color: #007700">)&nbsp;and&nbsp;</span><span style="color: #0000BB">$class</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">getMethod</span><span style="color: #007700">(</span><span style="color: #DD0000">'before'</span><span style="color: #007700">)-&gt;</span><span style="color: #0000BB">invoke</span><span style="color: #007700">(</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">controller_instance</span><span style="color: #007700">);</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">453</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line fuel_current_line"><span class="fuel_line_number">454</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$response&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">$action</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">invokeArgs</span><span style="color: #007700">(</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">controller_instance</span><span style="color: #007700">,&nbsp;</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">method_params</span><span style="color: #007700">);</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">455</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">456</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$class</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">hasMethod</span><span style="color: #007700">(</span><span style="color: #DD0000">'after'</span><span style="color: #007700">)&nbsp;and&nbsp;</span><span style="color: #0000BB">$response&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">$class</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">getMethod</span><span style="color: #007700">(</span><span style="color: #DD0000">'after'</span><span style="color: #007700">)-&gt;</span><span style="color: #0000BB">invoke</span><span style="color: #007700">(</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">controller_instance</span><span style="color: #007700">,&nbsp;</span><span style="color: #0000BB">$response</span><span style="color: #007700">);</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">457</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">458</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #FF8000">//&nbsp;fire&nbsp;any&nbsp;controller&nbsp;finished&nbsp;events</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">459</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">\</span><span style="color: #0000BB">Event</span><span style="color: #007700">::</span><span style="color: #0000BB">instance</span><span style="color: #007700">()-&gt;</span><span style="color: #0000BB">has_events</span><span style="color: #007700">(</span><span style="color: #DD0000">'controller_finished'</span><span style="color: #007700">)&nbsp;and&nbsp;\</span><span style="color: #0000BB">Event</span><span style="color: #007700">::</span><span style="color: #0000BB">instance</span><span style="color: #007700">()-&gt;</span><span style="color: #0000BB">trigger</span><span style="color: #007700">(</span><span style="color: #DD0000">'controller_finished'</span><span style="color: #007700">,&nbsp;</span><span style="color: #DD0000">''</span><span style="color: #007700">,&nbsp;</span><span style="color: #DD0000">'none'</span><span style="color: #007700">);</span></span>
</span></span></pre>
				</div>
			</li>
					<li>
				<a href="#" onclick="javascript:fuel_toggle('backtrace_10');return false;">DOCROOT/index.php @ line 71</a>
				<div id="backtrace_10" class="backtrace_block">
<pre class="fuel_debug_source"><span class="fuel_line"><span class="fuel_line_number">66</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$response&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">Response</span><span style="color: #007700">::</span><span style="color: #0000BB">forge</span><span style="color: #007700">(</span><span style="color: #0000BB">$response</span><span style="color: #007700">);</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">67</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">68</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">69</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">elseif&nbsp;(</span><span style="color: #0000BB">$e&nbsp;</span><span style="color: #007700">===&nbsp;</span><span style="color: #0000BB">false</span><span style="color: #007700">)</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">70</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">{</span></span>
</span></span><span class="fuel_line fuel_current_line"><span class="fuel_line_number">71</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$response&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">Request</span><span style="color: #007700">::</span><span style="color: #0000BB">forge</span><span style="color: #007700">()-&gt;</span><span style="color: #0000BB">execute</span><span style="color: #007700">()-&gt;</span><span style="color: #0000BB">response</span><span style="color: #007700">();</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">72</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">73</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">elseif&nbsp;(</span><span style="color: #0000BB">$route</span><span style="color: #007700">)</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">74</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">{</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">75</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$response&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">Request</span><span style="color: #007700">::</span><span style="color: #0000BB">forge</span><span style="color: #007700">(</span><span style="color: #0000BB">$route</span><span style="color: #007700">,&nbsp;</span><span style="color: #0000BB">false</span><span style="color: #007700">)-&gt;</span><span style="color: #0000BB">execute</span><span style="color: #007700">(array(</span><span style="color: #0000BB">$e</span><span style="color: #007700">))-&gt;</span><span style="color: #0000BB">response</span><span style="color: #007700">();</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">76</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span></pre>
				</div>
			</li>
					<li>
				<a href="#" onclick="javascript:fuel_toggle('backtrace_11');return false;">DOCROOT/index.php @ line 92</a>
				<div id="backtrace_11" class="backtrace_block">
<pre class="fuel_debug_source"><span class="fuel_line"><span class="fuel_line_number">87</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span><span style="color: #007700">{</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">88</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #FF8000">//&nbsp;Boot&nbsp;the&nbsp;app...</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">89</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">require&nbsp;</span><span style="color: #0000BB">APPPATH</span><span style="color: #007700">.</span><span style="color: #DD0000">'bootstrap.php'</span><span style="color: #007700">;</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">90</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">91</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #FF8000">//&nbsp;...&nbsp;and&nbsp;execute&nbsp;the&nbsp;main&nbsp;request</span></span>
</span></span><span class="fuel_line fuel_current_line"><span class="fuel_line_number">92</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;$response&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">$routerequest</span><span style="color: #007700">();</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">93</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">94</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span><span style="color: #007700">catch&nbsp;(</span><span style="color: #0000BB">HttpBadRequestException&nbsp;$e</span><span style="color: #007700">)</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">95</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span><span style="color: #007700">{</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">96</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;$response&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">$routerequest</span><span style="color: #007700">(</span><span style="color: #DD0000">'_400_'</span><span style="color: #007700">,&nbsp;</span><span style="color: #0000BB">$e</span><span style="color: #007700">);</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">97</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span><span style="color: #007700">}</span></span>
</span></span></pre>
				</div>
			</li>
				</ol>


	<h2>Prior Contents (<a href="#" onclick="javascript:fuel_toggle('prior_contents');return false;">show</a>)</h2>
				<pre id="prior_contents" class="fuel_debug_source" style="display: none;"> </pre>
	
		<p class="footer">
			<a href="http://fuelphp.com">FuelPHP</a> is released under the MIT license.
		</p>
	</div>
</body>
</html>
