<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>FuelPHP Framework</title>
	<style type="text/css">
		* { margin: 0; padding: 0; }
		body { background-color: #EEE; font-family: sans-serif; font-size: 16px; line-height: 20px; margin: 40px; }
		#wrapper { padding: 30px; background: #fff; color: #333; border: 1px solid #ccc; margin: 0 auto; width: 800px; }
		a { color: #36428D; }
		h1 { color: #000; font-size: 55px; padding: 0 0 25px; line-height: 1em; }
		.intro { font-size: 22px; line-height: 30px; font-family: georgia, serif; color: #555; padding: 29px 0 20px; border-top: 1px solid #CCC; }
		h2 { margin: 50px 0 15px; padding: 0 0 10px; font-size: 18px; border-bottom: 1px dashed #ccc; }
		h2.first { margin: 10px 0 15px; }
		p { margin: 0 0 15px; line-height: 22px;}
		a { color: #666; }
		pre { border-left: 1px solid #ddd; line-height:20px; margin:20px; padding-left:1em; font-size: 16px; }
		pre, code { color:#137F80; font-family: Courier, monospace; }
		ul, ol { margin: 15px 30px; }
		li { line-height: 24px;}
		.footer { color: #777; font-size: 12px; margin: 40px 0 0 0; }
		pre.fuel_debug_source { border: 1px solid #CCCCCC; background-color: #FFFFFF; color: #333333; font-family: monospace; font-size: 11px; line-height: 1em; margin: 0; padding: 0; width: 100%; overflow: auto; }
		span.fuel_line { display: block; margin: 0px; padding: 0px; }
		span.fuel_line_number { display: inline-block; background-color: #EFEFEF; padding: 4px 8px 4px 8px; }
		span.fuel_line_content { display: inline-block; padding: 4px 0 4px 4px; }
		span.fuel_current_line span.fuel_line_number, span.fuel_current_line { background-color: #f0eb96; font-weight: bold; }
		.backtrace_block { display: none; }
	</style>
	<script type="text/javascript">
		function fuel_toggle(elem){elem = document.getElementById(elem);if (elem.style && elem.style['display']){var disp = elem.style['display'];}else if (elem.currentStyle){var disp = elem.currentStyle['display'];}else if (window.getComputedStyle){var disp = document.defaultView.getComputedStyle(elem, null).getPropertyValue('display');}elem.style.display = disp == 'block' ? 'none' : 'block';return false;}
	</script>
</head>
<body>
	<div id="wrapper">
		<h1>23000!</h1>

		<p class="intro">Fuel\Core\Database_Exception [ 23000 ]:<br />SQLSTATE[23000]: Integrity constraint violation: 1048 Column &#039;id_role&#039; cannot be null with query: &quot;INSERT INTO `users` (`name`, `password`, `id_role`) VALUES (&#039;jose&#039;, &#039;1234&#039;, null)&quot;</p>

		<h2 class="first">COREPATH/classes/database/pdo/connection.php @ line 253</h2>

<pre class="fuel_debug_source"><span class="fuel_line"><span class="fuel_line_number">248</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">{</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">249</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$error_code&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">0</span><span style="color: #007700">;</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">250</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">251</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">252</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line fuel_current_line"><span class="fuel_line_number">253</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">throw&nbsp;new&nbsp;\</span><span style="color: #0000BB">Database_Exception</span><span style="color: #007700">(</span><span style="color: #0000BB">$e</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">getMessage</span><span style="color: #007700">().</span><span style="color: #DD0000">'&nbsp;with&nbsp;query:&nbsp;"'</span><span style="color: #007700">.</span><span style="color: #0000BB">$sql</span><span style="color: #007700">.</span><span style="color: #DD0000">'"'</span><span style="color: #007700">,&nbsp;</span><span style="color: #0000BB">$error_code</span><span style="color: #007700">,&nbsp;</span><span style="color: #0000BB">$e</span><span style="color: #007700">);</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">254</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">255</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">256</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">257</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #FF8000">//&nbsp;no&nbsp;more&nbsp;attempts&nbsp;left,&nbsp;bail&nbsp;out</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">258</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">else</span></span>
</span></span></pre>
		<h2>Backtrace</h2>
		<ol>
					<li>
				<a href="#" onclick="javascript:fuel_toggle('backtrace_1');return false;">COREPATH/classes/database/query.php @ line 314</a>
				<div id="backtrace_1" class="backtrace_block">
<pre class="fuel_debug_source"><span class="fuel_line"><span class="fuel_line_number">309</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">catch&nbsp;(\</span><span style="color: #0000BB">CacheNotFoundException&nbsp;$e</span><span style="color: #007700">)&nbsp;{}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">310</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">311</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">312</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #FF8000">//&nbsp;Execute&nbsp;the&nbsp;query</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">313</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">\</span><span style="color: #0000BB">DB</span><span style="color: #007700">::</span><span style="color: #0000BB">$query_count</span><span style="color: #007700">++;</span></span>
</span></span><span class="fuel_line fuel_current_line"><span class="fuel_line_number">314</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$result&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">$db</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">query</span><span style="color: #007700">(</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">_type</span><span style="color: #007700">,&nbsp;</span><span style="color: #0000BB">$sql</span><span style="color: #007700">,&nbsp;</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">_as_object</span><span style="color: #007700">);</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">315</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">316</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #FF8000">//&nbsp;Cache&nbsp;the&nbsp;result&nbsp;if&nbsp;needed</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">317</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">if&nbsp;(isset(</span><span style="color: #0000BB">$cache</span><span style="color: #007700">)&nbsp;and&nbsp;(</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">_cache_all&nbsp;</span><span style="color: #007700">or&nbsp;</span><span style="color: #0000BB">$result</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">count</span><span style="color: #007700">()))</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">318</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">{</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">319</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$cache</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">set_expiration</span><span style="color: #007700">(</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">_lifetime</span><span style="color: #007700">)-&gt;</span><span style="color: #0000BB">set_contents</span><span style="color: #007700">(</span><span style="color: #0000BB">$result</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">as_array</span><span style="color: #007700">())-&gt;</span><span style="color: #0000BB">set</span><span style="color: #007700">();</span></span>
</span></span></pre>
				</div>
			</li>
					<li>
				<a href="#" onclick="javascript:fuel_toggle('backtrace_2');return false;">PKGPATH/orm/classes/query.php @ line 1505</a>
				<div id="backtrace_2" class="backtrace_block">
<pre class="fuel_debug_source"><span class="fuel_line"><span class="fuel_line_number">1500</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">*/</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">1501</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">public&nbsp;function&nbsp;</span><span style="color: #0000BB">insert</span><span style="color: #007700">()</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">1502</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">{</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">1503</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$res&nbsp;</span><span style="color: #007700">=&nbsp;\</span><span style="color: #0000BB">DB</span><span style="color: #007700">::</span><span style="color: #0000BB">insert</span><span style="color: #007700">(</span><span style="color: #0000BB">call_user_func</span><span style="color: #007700">(</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">model</span><span style="color: #007700">.</span><span style="color: #DD0000">'::table'</span><span style="color: #007700">),&nbsp;</span><span style="color: #0000BB">array_keys</span><span style="color: #007700">(</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">values</span><span style="color: #007700">))</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">1504</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">values</span><span style="color: #007700">(</span><span style="color: #0000BB">array_values</span><span style="color: #007700">(</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">values</span><span style="color: #007700">))</span></span>
</span></span><span class="fuel_line fuel_current_line"><span class="fuel_line_number">1505</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">execute</span><span style="color: #007700">(</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">write_connection</span><span style="color: #007700">);</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">1506</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">1507</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #FF8000">//&nbsp;Failed&nbsp;to&nbsp;save&nbsp;the&nbsp;new&nbsp;record</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">1508</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">if&nbsp;(</span><span style="color: #0000BB">$res</span><span style="color: #007700">[</span><span style="color: #0000BB">1</span><span style="color: #007700">]&nbsp;===&nbsp;</span><span style="color: #0000BB">0</span><span style="color: #007700">)</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">1509</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">{</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">1510</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">return&nbsp;</span><span style="color: #0000BB">false</span><span style="color: #007700">;</span></span>
</span></span></pre>
				</div>
			</li>
					<li>
				<a href="#" onclick="javascript:fuel_toggle('backtrace_3');return false;">PKGPATH/orm/classes/model.php @ line 1390</a>
				<div id="backtrace_3" class="backtrace_block">
<pre class="fuel_debug_source"><span class="fuel_line"><span class="fuel_line_number">1385</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$query</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">set</span><span style="color: #007700">(</span><span style="color: #0000BB">$p</span><span style="color: #007700">,&nbsp;</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;{</span><span style="color: #0000BB">$p</span><span style="color: #007700">});</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">1386</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">1387</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">1388</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">1389</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #FF8000">//&nbsp;Insert!</span></span>
</span></span><span class="fuel_line fuel_current_line"><span class="fuel_line_number">1390</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$id&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">$query</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">insert</span><span style="color: #007700">();</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">1391</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">1392</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #FF8000">//&nbsp;when&nbsp;there's&nbsp;one&nbsp;PK&nbsp;it&nbsp;might&nbsp;be&nbsp;auto-incremented,&nbsp;get&nbsp;it&nbsp;and&nbsp;set&nbsp;it</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">1393</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">if&nbsp;(</span><span style="color: #0000BB">count</span><span style="color: #007700">(</span><span style="color: #0000BB">$primary_key</span><span style="color: #007700">)&nbsp;==&nbsp;</span><span style="color: #0000BB">1&nbsp;</span><span style="color: #007700">and&nbsp;</span><span style="color: #0000BB">$id&nbsp;</span><span style="color: #007700">!==&nbsp;</span><span style="color: #0000BB">false</span><span style="color: #007700">)</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">1394</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">{</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">1395</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$pk&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">reset</span><span style="color: #007700">(</span><span style="color: #0000BB">$primary_key</span><span style="color: #007700">);</span></span>
</span></span></pre>
				</div>
			</li>
					<li>
				<a href="#" onclick="javascript:fuel_toggle('backtrace_4');return false;">PKGPATH/orm/classes/model.php @ line 1336</a>
				<div id="backtrace_4" class="backtrace_block">
<pre class="fuel_debug_source"><span class="fuel_line"><span class="fuel_line_number">1331</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">1332</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">1333</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">unfreeze</span><span style="color: #007700">();</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">1334</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">1335</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #FF8000">//&nbsp;Insert&nbsp;or&nbsp;update</span></span>
</span></span><span class="fuel_line fuel_current_line"><span class="fuel_line_number">1336</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$return&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">_is_new&nbsp;</span><span style="color: #007700">?&nbsp;</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">create</span><span style="color: #007700">()&nbsp;:&nbsp;</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">update</span><span style="color: #007700">();</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">1337</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">1338</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">freeze</span><span style="color: #007700">();</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">1339</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">foreach(</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">relations</span><span style="color: #007700">()&nbsp;as&nbsp;</span><span style="color: #0000BB">$rel_name&nbsp;</span><span style="color: #007700">=&gt;&nbsp;</span><span style="color: #0000BB">$rel</span><span style="color: #007700">)</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">1340</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">{</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">1341</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">if&nbsp;(</span><span style="color: #0000BB">array_key_exists</span><span style="color: #007700">(</span><span style="color: #0000BB">$rel_name</span><span style="color: #007700">,&nbsp;</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">_data_relations</span><span style="color: #007700">))</span></span>
</span></span></pre>
				</div>
			</li>
					<li>
				<a href="#" onclick="javascript:fuel_toggle('backtrace_5');return false;">APPPATH/classes/controller/users.php @ line 34</a>
				<div id="backtrace_5" class="backtrace_block">
<pre class="fuel_debug_source"><span class="fuel_line"><span class="fuel_line_number">29</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">30</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$user&nbsp;</span><span style="color: #007700">=&nbsp;new&nbsp;</span><span style="color: #0000BB">Model_Users</span><span style="color: #007700">();</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">31</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$user</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">name&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">$name</span><span style="color: #007700">;</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">32</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$user</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">password&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">$password</span><span style="color: #007700">;</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">33</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$user</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">role&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">Model_Roles</span><span style="color: #007700">::</span><span style="color: #0000BB">find</span><span style="color: #007700">(</span><span style="color: #0000BB">$role</span><span style="color: #007700">);</span></span>
</span></span><span class="fuel_line fuel_current_line"><span class="fuel_line_number">34</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$user</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">save</span><span style="color: #007700">();</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">35</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$json&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">response</span><span style="color: #007700">(array(</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">36</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #DD0000">'code'&nbsp;</span><span style="color: #007700">=&gt;&nbsp;</span><span style="color: #0000BB">201</span><span style="color: #007700">,</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">37</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #DD0000">'message'&nbsp;</span><span style="color: #007700">=&gt;&nbsp;</span><span style="color: #DD0000">'usuario&nbsp;creado'</span><span style="color: #007700">,</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">38</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #DD0000">'name'&nbsp;</span><span style="color: #007700">=&gt;&nbsp;</span><span style="color: #0000BB">$input</span><span style="color: #007700">[</span><span style="color: #DD0000">'name'</span><span style="color: #007700">],</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">39</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">));</span></span>
</span></span></pre>
				</div>
			</li>
					<li>
				<a href="#" onclick="javascript:fuel_toggle('backtrace_6');return false;">COREPATH/base56.php @ line 37</a>
				<div id="backtrace_6" class="backtrace_block">
<pre class="fuel_debug_source"><span class="fuel_line"><span class="fuel_line_number">32</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$args&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">array_values</span><span style="color: #007700">(</span><span style="color: #0000BB">$args</span><span style="color: #007700">);</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">33</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">34</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">35</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">list(</span><span style="color: #0000BB">$instance</span><span style="color: #007700">,&nbsp;</span><span style="color: #0000BB">$method</span><span style="color: #007700">)&nbsp;=&nbsp;</span><span style="color: #0000BB">$callback</span><span style="color: #007700">;</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">36</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line fuel_current_line"><span class="fuel_line_number">37</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">return&nbsp;</span><span style="color: #0000BB">$instance</span><span style="color: #007700">-&gt;{</span><span style="color: #0000BB">$method</span><span style="color: #007700">}(...</span><span style="color: #0000BB">$args</span><span style="color: #007700">);</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">38</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">39</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">40</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #FF8000">//&nbsp;static&nbsp;call?</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">41</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">elseif&nbsp;(</span><span style="color: #0000BB">is_array</span><span style="color: #007700">(</span><span style="color: #0000BB">$callback</span><span style="color: #007700">)&nbsp;and&nbsp;isset(</span><span style="color: #0000BB">$callback</span><span style="color: #007700">[</span><span style="color: #0000BB">1</span><span style="color: #007700">])&nbsp;and&nbsp;</span><span style="color: #0000BB">is_string</span><span style="color: #007700">(</span><span style="color: #0000BB">$callback</span><span style="color: #007700">[</span><span style="color: #0000BB">0</span><span style="color: #007700">]))</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">42</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">{</span></span>
</span></span></pre>
				</div>
			</li>
					<li>
				<a href="#" onclick="javascript:fuel_toggle('backtrace_7');return false;">COREPATH/classes/controller/rest.php @ line 153</a>
				<div id="backtrace_7" class="backtrace_block">
<pre class="fuel_debug_source"><span class="fuel_line"><span class="fuel_line_number">148</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">149</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">150</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #FF8000">//&nbsp;If&nbsp;method&nbsp;is&nbsp;not&nbsp;available,&nbsp;set&nbsp;status&nbsp;code&nbsp;to&nbsp;404</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">151</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">if&nbsp;(</span><span style="color: #0000BB">method_exists</span><span style="color: #007700">(</span><span style="color: #0000BB">$this</span><span style="color: #007700">,&nbsp;</span><span style="color: #0000BB">$controller_method</span><span style="color: #007700">))</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">152</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">{</span></span>
</span></span><span class="fuel_line fuel_current_line"><span class="fuel_line_number">153</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">return&nbsp;</span><span style="color: #0000BB">call_fuel_func_array</span><span style="color: #007700">(array(</span><span style="color: #0000BB">$this</span><span style="color: #007700">,&nbsp;</span><span style="color: #0000BB">$controller_method</span><span style="color: #007700">),&nbsp;</span><span style="color: #0000BB">$arguments</span><span style="color: #007700">);</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">154</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">155</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">else</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">156</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">{</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">157</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">response</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">status&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">no_method_status</span><span style="color: #007700">;</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">158</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">return;</span></span>
</span></span></pre>
				</div>
			</li>
					<li>
				<a href="#" onclick="javascript:fuel_toggle('backtrace_8');return false;">COREPATH/classes/request.php @ line 454</a>
				<div id="backtrace_8" class="backtrace_block">
<pre class="fuel_debug_source"><span class="fuel_line"><span class="fuel_line_number">449</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #FF8000">//&nbsp;fire&nbsp;any&nbsp;controller&nbsp;started&nbsp;events</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">450</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">\</span><span style="color: #0000BB">Event</span><span style="color: #007700">::</span><span style="color: #0000BB">instance</span><span style="color: #007700">()-&gt;</span><span style="color: #0000BB">has_events</span><span style="color: #007700">(</span><span style="color: #DD0000">'controller_started'</span><span style="color: #007700">)&nbsp;and&nbsp;\</span><span style="color: #0000BB">Event</span><span style="color: #007700">::</span><span style="color: #0000BB">instance</span><span style="color: #007700">()-&gt;</span><span style="color: #0000BB">trigger</span><span style="color: #007700">(</span><span style="color: #DD0000">'controller_started'</span><span style="color: #007700">,&nbsp;</span><span style="color: #DD0000">''</span><span style="color: #007700">,&nbsp;</span><span style="color: #DD0000">'none'</span><span style="color: #007700">);</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">451</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">452</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$class</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">hasMethod</span><span style="color: #007700">(</span><span style="color: #DD0000">'before'</span><span style="color: #007700">)&nbsp;and&nbsp;</span><span style="color: #0000BB">$class</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">getMethod</span><span style="color: #007700">(</span><span style="color: #DD0000">'before'</span><span style="color: #007700">)-&gt;</span><span style="color: #0000BB">invoke</span><span style="color: #007700">(</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">controller_instance</span><span style="color: #007700">);</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">453</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line fuel_current_line"><span class="fuel_line_number">454</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$response&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">$action</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">invokeArgs</span><span style="color: #007700">(</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">controller_instance</span><span style="color: #007700">,&nbsp;</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">method_params</span><span style="color: #007700">);</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">455</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">456</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$class</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">hasMethod</span><span style="color: #007700">(</span><span style="color: #DD0000">'after'</span><span style="color: #007700">)&nbsp;and&nbsp;</span><span style="color: #0000BB">$response&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">$class</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">getMethod</span><span style="color: #007700">(</span><span style="color: #DD0000">'after'</span><span style="color: #007700">)-&gt;</span><span style="color: #0000BB">invoke</span><span style="color: #007700">(</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">controller_instance</span><span style="color: #007700">,&nbsp;</span><span style="color: #0000BB">$response</span><span style="color: #007700">);</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">457</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">458</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #FF8000">//&nbsp;fire&nbsp;any&nbsp;controller&nbsp;finished&nbsp;events</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">459</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">\</span><span style="color: #0000BB">Event</span><span style="color: #007700">::</span><span style="color: #0000BB">instance</span><span style="color: #007700">()-&gt;</span><span style="color: #0000BB">has_events</span><span style="color: #007700">(</span><span style="color: #DD0000">'controller_finished'</span><span style="color: #007700">)&nbsp;and&nbsp;\</span><span style="color: #0000BB">Event</span><span style="color: #007700">::</span><span style="color: #0000BB">instance</span><span style="color: #007700">()-&gt;</span><span style="color: #0000BB">trigger</span><span style="color: #007700">(</span><span style="color: #DD0000">'controller_finished'</span><span style="color: #007700">,&nbsp;</span><span style="color: #DD0000">''</span><span style="color: #007700">,&nbsp;</span><span style="color: #DD0000">'none'</span><span style="color: #007700">);</span></span>
</span></span></pre>
				</div>
			</li>
					<li>
				<a href="#" onclick="javascript:fuel_toggle('backtrace_9');return false;">DOCROOT/index.php @ line 71</a>
				<div id="backtrace_9" class="backtrace_block">
<pre class="fuel_debug_source"><span class="fuel_line"><span class="fuel_line_number">66</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$response&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">Response</span><span style="color: #007700">::</span><span style="color: #0000BB">forge</span><span style="color: #007700">(</span><span style="color: #0000BB">$response</span><span style="color: #007700">);</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">67</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">68</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">69</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">elseif&nbsp;(</span><span style="color: #0000BB">$e&nbsp;</span><span style="color: #007700">===&nbsp;</span><span style="color: #0000BB">false</span><span style="color: #007700">)</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">70</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">{</span></span>
</span></span><span class="fuel_line fuel_current_line"><span class="fuel_line_number">71</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$response&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">Request</span><span style="color: #007700">::</span><span style="color: #0000BB">forge</span><span style="color: #007700">()-&gt;</span><span style="color: #0000BB">execute</span><span style="color: #007700">()-&gt;</span><span style="color: #0000BB">response</span><span style="color: #007700">();</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">72</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">73</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">elseif&nbsp;(</span><span style="color: #0000BB">$route</span><span style="color: #007700">)</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">74</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">{</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">75</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$response&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">Request</span><span style="color: #007700">::</span><span style="color: #0000BB">forge</span><span style="color: #007700">(</span><span style="color: #0000BB">$route</span><span style="color: #007700">,&nbsp;</span><span style="color: #0000BB">false</span><span style="color: #007700">)-&gt;</span><span style="color: #0000BB">execute</span><span style="color: #007700">(array(</span><span style="color: #0000BB">$e</span><span style="color: #007700">))-&gt;</span><span style="color: #0000BB">response</span><span style="color: #007700">();</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">76</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">}</span></span>
</span></span></pre>
				</div>
			</li>
					<li>
				<a href="#" onclick="javascript:fuel_toggle('backtrace_10');return false;">DOCROOT/index.php @ line 92</a>
				<div id="backtrace_10" class="backtrace_block">
<pre class="fuel_debug_source"><span class="fuel_line"><span class="fuel_line_number">87</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span><span style="color: #007700">{</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">88</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #FF8000">//&nbsp;Boot&nbsp;the&nbsp;app...</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">89</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">require&nbsp;</span><span style="color: #0000BB">APPPATH</span><span style="color: #007700">.</span><span style="color: #DD0000">'bootstrap.php'</span><span style="color: #007700">;</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">90</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">91</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #FF8000">//&nbsp;...&nbsp;and&nbsp;execute&nbsp;the&nbsp;main&nbsp;request</span></span>
</span></span><span class="fuel_line fuel_current_line"><span class="fuel_line_number">92</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;$response&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">$routerequest</span><span style="color: #007700">();</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">93</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span><span style="color: #007700">}</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">94</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span><span style="color: #007700">catch&nbsp;(</span><span style="color: #0000BB">HttpBadRequestException&nbsp;$e</span><span style="color: #007700">)</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">95</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span><span style="color: #007700">{</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">96</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;$response&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">$routerequest</span><span style="color: #007700">(</span><span style="color: #DD0000">'_400_'</span><span style="color: #007700">,&nbsp;</span><span style="color: #0000BB">$e</span><span style="color: #007700">);</span></span>
</span></span><span class="fuel_line"><span class="fuel_line_number">97</span><span class="fuel_line_content"><span style="color: #000000"><span style="color: #0000BB"></span><span style="color: #007700">}</span></span>
</span></span></pre>
				</div>
			</li>
				</ol>


	<h2>Prior Contents (<a href="#" onclick="javascript:fuel_toggle('prior_contents');return false;">show</a>)</h2>
				<pre id="prior_contents" class="fuel_debug_source" style="display: none;"> </pre>
	
		<p class="footer">
			<a href="http://fuelphp.com">FuelPHP</a> is released under the MIT license.
		</p>
	</div>
</body>
</html>
